title: Radialle
email: contato@rlaneth.com
description: >-
  O Radialle foi um grupo de estudos e publicações em tecnologia da informação
  criado em 2016 e encerrado em 2020. Este site é dedicado a preservar o
  material por ele produzido durante seu tempo de atividade.
baseurl: ""
url: ""
github_username:  radialle

# Build settings
theme: minima